#!/usr/bin/env bash
# Sync local game/ mods to Luanti and restart the Aracdia client + local server.
#
# Usage (from repo root):
#   ./scripts/dev-reload-game.sh
#
# Requires the engine installed by the Aracdia launcher (JOUER at least once).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GAME_SRC="$ROOT/game"

if [[ "$(uname -s)" == "Darwin" ]]; then
  LAUNCHER_DATA="$HOME/Library/Application Support/com.Aracdia.Launcher"
  LUANTI_GAMES="$HOME/Library/Application Support/minetest/games"
  ENGINE_BIN="$LAUNCHER_DATA/engine/luanti.app/Contents/MacOS/luanti"
else
  LAUNCHER_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/aracdia-launcher"
  LUANTI_GAMES="$HOME/.minetest/games"
  ENGINE_BIN="$LAUNCHER_DATA/engine/bin/luanti"
fi

PROFILE_JSON="$LAUNCHER_DATA/profile.json"
SETTINGS_JSON="$LAUNCHER_DATA/settings.json"
WORLD_DIR="$LAUNCHER_DATA/worlds/aracdia"
SERVER_CONF="$LAUNCHER_DATA/server.conf"
GAME_DEST="$LUANTI_GAMES/aracdia"
LOG_DIR="$LAUNCHER_DATA/logs/dev-reload"

die() { echo "dev-reload-game: $*" >&2; exit 1; }

[[ -d "$GAME_SRC" ]] || die "game source not found at $GAME_SRC"
[[ -x "$ENGINE_BIN" ]] || die "engine not installed — launch the Aracdia launcher and click JOUER once"
[[ -f "$PROFILE_JSON" ]] || die "profile.json missing — log in through the launcher first"

mkdir -p "$LOG_DIR" "$LUANTI_GAMES"

echo "[1/4] Syncing game/ → $GAME_DEST"
rm -rf "$GAME_DEST"
cp -R "$GAME_SRC" "$GAME_DEST"
rm -f "$GAME_DEST/.aracdia-content-version"

read_json() {
  python3 - "$1" "$2" <<'PY'
import json, sys
path, key = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    data = json.load(f)
# camelCase keys from the launcher JSON files
aliases = {
    "username": ("username",),
    "localServerPort": ("localServerPort", "local_server_port"),
    "localServerBind": ("localServerBind", "local_server_bind"),
}
for k in aliases.get(key, (key,)):
    if k in data:
        print(data[k])
        break
else:
    sys.exit(1)
PY
}

USERNAME="$(read_json "$PROFILE_JSON" username)"
PORT="$(read_json "$SETTINGS_JSON" localServerPort)"
BIND="$(read_json "$SETTINGS_JSON" localServerBind)"

SERVER_LOG="$LOG_DIR/server-$(date +%Y%m%d-%H%M%S).log"
CLIENT_LOG="$LOG_DIR/client-$(date +%Y%m%d-%H%M%S).log"

stop_launcher_engine() {
  echo "[2/4] Stopping running Aracdia engine processes"
  # Only touch processes spawned from the launcher-managed engine install.
  local pattern
  pattern="$(printf '%s' "$ENGINE_BIN" | sed 's/[.[\^$()*+?{|]/\\&/g')"
  pkill -f "$pattern" 2>/dev/null || true
  sleep 1
  pkill -9 -f "$pattern" 2>/dev/null || true
  rm -f "$LAUNCHER_DATA/session.json" "$LAUNCHER_DATA/server-session.json"
}

write_server_conf() {
  cat >"$SERVER_CONF" <<EOF
# Auto-generated by dev-reload-game.sh — overwritten on each reload.
bind_address = ${BIND}
port = ${PORT}
time_speed = 0
EOF
}

wait_for_server() {
  local log="$1"
  local pid="$2"
  for ((i = 1; i <= 120; i++)); do
    if [[ -f "$log" ]] && grep -q 'Server for gameid=' "$log"; then
      sleep 2
      return 0
    fi
    if ! kill -0 "$pid" 2>/dev/null; then
      echo "Server process exited early. Last log lines:" >&2
      tail -n 40 "$log" >&2 || true
      return 1
    fi
    sleep 0.25
  done
  return 1
}

stop_launcher_engine

echo "[3/4] Starting local server (port ${PORT})"
write_server_conf
nohup "$ENGINE_BIN" \
  --server \
  --world "$WORLD_DIR" \
  --gameid aracdia \
  --config "$SERVER_CONF" \
  --port "$PORT" \
  >>"$SERVER_LOG" 2>&1 &
SERVER_PID=$!

if ! wait_for_server "$SERVER_LOG" "$SERVER_PID"; then
  kill "$SERVER_PID" 2>/dev/null || true
  die "server did not become ready (port ${PORT})"
fi

echo "[4/4] Starting client (${USERNAME} → 127.0.0.1:${PORT})"
nohup "$ENGINE_BIN" \
  --name "$USERNAME" \
  --address 127.0.0.1 \
  --port "$PORT" \
  --go \
  >>"$CLIENT_LOG" 2>&1 &

echo "Done."
echo "  server log: $SERVER_LOG"
echo "  client log: $CLIENT_LOG"
echo "  game dest:  $GAME_DEST"
